# >------------------------------------------------------------------------------------------------------------< #
#                                              NPC Messages ~                                                    #
#                                                                           A Plugin by KAMKEEL                  #
# >---------------------------------------------- Config ------------------------------------------------------< #
#                                                                                                                #
# If this config becomes corrupted, please delete it.                                                            #
#                                                                                                                #
# What is in this config?                                                                                        #
#       - Data Storage                                                                                           #
#       - Format for Chat Messages                                                                               #
#       - Time before deleting a fake name                                                                       #
#                                                                                                                #
# So? What should I do?                                                                                          #
#       - You can edit the ChatFormat: tag, to match whatever your server chat looks like.                       #
#         Due to file limitations, you must use the '+' to denote color. Spaces will be used as specified.       #
#         Use '%FM%' as a placeholder for the fake name, and %MSG% as a placeholder for the message.             #
#       - You can also edit the Time: tag, (Please specify NUMBERS only!) to the time (in minutes) to clear      #
#         remove a fake name created with /fma.                                                                  #
#                                                                                                                #
# What should I NOT do?                                                                                          #
#       - Don't mess with the NPCs tag. This could corrupt your server.                                          #
# >------------------------------------------ End of Readable Part --------------------------------------------< #
#
ChatFormat: <%FM%+r> %MSG%
Time: 15
NPCs: