name: RPGMessenger
author: KAMKEEL
main: kamkeel.RPGMessenger.RPGMessenger
version: 1.1
description: RPG Messenger | A plugin to allow NPC, Fake Names and Broadcast Messengening for RPG Servers
commands:
  npc:
    description: View and modify the server NPCs
    usage: |
      /npc <add/remove> <Name> - Add or Delete NPCs
      /npc clear - Removes All NPCs
      /npc rename <ID> <Name> - Rename an NPC
      /npc swap <ID> <ID> - Swap NPC IDs
      /npc list <pageNum> - List all Active NPCs
      /npc id <Name> or /npcid <Name> - Search for an NPCs ID
    aliases: npcid
    permission: rpg.npc
    permission-message: §cSorry! You don't have permission to execute that command.
  action:
    description: Sends a global message
    usage: |
      /action help
    permission: rpg.npc
    aliases: [actionsay, as, cbm]
    permission-message: §cSorry! You don't have permission to execute that command.
  npcmsg:
    description: Sends a player a private message
    usage: |
      /npcmsg <npcName/npcID> <player> <message>
      /npcreply <player> <message>
    permission: rpg.npc
    aliases: [idm, nms, nm, npcm, npcreply, npcr, nr, npcsay, npcs, ns]
    permission-message: §cSorry! You don't have permission to execute that command.
  groupmsg:
    description: Sends a group a private message as an NPC
    usage: |
      /groupmsg <npcName/npcID> <groupName..Tag..ID> <message>
      /groupreply <groupName..Tag..ID> <message>
    permission: rpg.npc
    aliases: [idg, groupm, groupreply, grouprr, gr]
    permission-message: §cSorry! You don't have permission to execute that command.
  localmsg:
    description: Sends a group a private message as an NPC
    usage: |
      /localmsg <npcName/npcID> <Player> <message>
    permission: rpg.npc
    aliases: [idl, localm, lm, pm, idp]
    permission-message: §cSorry! You don't have permission to execute that command.
  role:
    description: Allows for Fake Name set for messaging and outloud chat
    usage: |
      /role id <#> - Sets RPG name using an NPC id
      /role name <NAME> - Sets RPG name using custom Name
      /role msg <Player> <Text> - Messages a player using your fake rpg name
      /role say <Text> - Talks to public chat using your fake rpg name
      /role list <#> - Displays current Role Names
    permission: rpg.role
    permission-message: §cSorry! You don't have permission to execute that command.
  tmp:
    description: Allows for Fake Name set for messaging and outloud chat
    usage: |
      /tmpmsg or /tm <NAME> <Player> <Text> - Messages a player using a temporary npc name
      /tmpgroup or /tg <NAME> <Group> <Text> - Messages a Group using a temporary npc name
      /tmplocal or /tl <NAME> <Player> <Text> - Messages a player local using a temporary npc name
      /tmpsay or /ts <NAME> <Text> - Talks to public chat using a temporary npc name
      /tmplist or /tlist <Player> <Text> - Displays all curent temporary NPC names
      /tmphelp - Displays All Commands
    permission: rpg.tmp
    aliases: [tmpmsg, tm, fma, tma, tidm, tmplocal, tl, lma, tla, tidl, tidp, tmpgroup, tidg, tga, tmppublic, tmpsay, ts, tsa, tmplist, tlist, tmphelp]
    permission-message: §cSorry! You don't have permission to execute that command.
  msg:
    description: Sends a player a private message
    usage: /msg <player> <message>
    aliases: [pm,m,t,emsg,epm,tell,etell,ewhisper,w, whisper, message]
  gmsg:
    description: Sends a group a private message
    usage: /gmsg <groupName..Tag..ID> <message>
    aliases: [groupmessage, gid, gmessage]
  pmsg:
    description: Sends a private public (local) message
    usage: /pmsg <message>
    aliases: [lmsg, publicmessage, localmessage, lmessage, pmessage]
  reply:
    description: Quickly reply to a message
    usage: /reply <msg>
    aliases: [r, er, reply, ereply]
  group:
    description: View and modify the server Groups
    usage: /group help
    aliases: group
  rpg:
    description: View RPG Commands
    usage: /rpg help
    aliases: rpg
  request:
    description: View request Commands
    usage: /request help
    aliases: request
permsissions:
  rpg.npc:
    default: op
  rpg.spy:
   default: op
  rpg.admin:
    default: op
  rpg.group:
    default: op
  rpg.*:
    children:
      rpg.npc
      rpg.group
      rpg.spy
      rpg.admin
      rpg.role