name: RPGMessenger
author: KAMKEEL
main: kamkeel.RPGMessenger.RPGMessenger
version: 1.0
description: RPG Messenger | A plugin to allow NPC, Fake Names and Broadcast Messengening for RPG Servers
commands:
  npc:
    description: View and modify the server NPCs
    usage: |
      /npc <add/remove> <Name> - Add or Delete NPCs
      /npc clear - Removes All NPCs
      /npc rename <ID> <Name> - Rename an NPC
      /npc swap <ID> <ID> - Swap NPC IDs
      /npc list <pageNum> - List all Active NPCs
      /npc id <Name> or /npcid <Name> - Search for an NPCs ID
    aliases: npcid
    permission: rpg.npc
    permission-message: Sorry! You don't have permission to execute that command.
  rpg:
    description: Allows for Fake Name set for messaging and outloud chat
    usage: |
      /rpg id <#> - Sets RPG name using an NPC id
      /rpg name <NAME> - Sets RPG name using custom Name
      /rpg msg <Player> <Text> - Messages a player using your fake rpg name
      /rpg say <Text> - Talks to public chat using your fake rpg name
    permission: rpg.fake
    permission-message: Sorry! You don't have permission to execute that command.
  fm: 
    description: Sends a message with your fakename!
    usage: /fm <Player> <Message>
    permission: fm.send
    aliases: fakemessage
  msg:
    description: Sends a player a private message
    usage: /msg <player> <message>
    aliases: [pm,m,t,emsg,epm,tell,etell,ewhisper,w, whisper]
  gmsg:
    description: Sends a group a private message
    usage: /gmsg <group> <message>
    aliases: [groupmessage, gid]
  r:
    description: Quickly reply to a message
    usage: /r <msg>
    aliases: [er, reply, ereply]
  gr:
    description: Quickly reply to a group message
    usage: /gr <msg>
    aliases: []
  nr:
    description: Quickly reply to a message using an NPC
    usage: /nr <Player> <msg>
    aliases: []
    permission: fm.send
  group:
    description: View and modify the server Groups
    usage: /group help
    aliases: group
  fs: 
    description: Sends a public chat message with your fake name
    usage: /fs <Message>
    permission: fm.send
    aliases: fakesay
  fma: 
    description: Sends an npc a message as another player
    usage: /fma <Fake Name> <Player> <Message>
    permission: fm.send
    aliases: [idm, fakemessageas, nma]
  fga:
    description: Sends an npc a message as another group
    usage: /fga <NPCName> <Group> <Message>
    permission: fm.send
    aliases: [idig, idg, ng, nga, fgan]
  fsa:
    description: Send a public message with a fake name
    usage: /fsa <Fake Name> <Message>
    permission: fm.send
    aliases: [fakesayas,fsid]
permsissions:
  rpg.npc:
    default: op
  rpg.spy:
   default: op
  rpg.*:
    children:
      rpg.npc
      rpg.group
      rpg.fake
      rpg.spy
  fm.name: 
   default: op
  fm.send:
   default: op
  fm.npc:
   default: op
  fm.group:
    default: op
  fm.*: 
   children:
    fm.name
    fm.send
    fm.npc
    fm.spy